// Auto-generated by Ghidra Script DO NOT MODIFY

#include <stdint.h>
#if __has_include(<Python.h>)
    #define BUILDING_PYTHON_EXTENSION 1
#endif

#ifdef BUILDING_PYTHON_EXTENSION
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#endif

typedef unsigned long ulong;
typedef unsigned int uint;
typedef unsigned char undefined;
typedef unsigned short undefined2;
typedef unsigned int undefined4;
typedef unsigned long undefined8;

typedef enum Protocol__Enum {
    Protocol__Enum_Common_Cheat = -9999,
    Protocol__Enum_Error = -1,
    Protocol__Enum_None = 0,
    Protocol__Enum_System_Version = 1,
    Protocol__Enum_Session_Info = 2,
    Protocol__Enum_NetworkTime_Sync = 3,
    Protocol__Enum_NetworkTime_SyncReply = 4,
    Protocol__Enum_Audit_GachaStatistics = 5,
    Protocol__Enum_Account_Create = 1000,
    Protocol__Enum_Account_Nickname = 1001,
    Protocol__Enum_Account_Auth = 1002,
    Protocol__Enum_Account_CurrencySync = 1003,
    Protocol__Enum_Account_SetRepresentCharacterAndComment = 1004,
    Protocol__Enum_Account_GetTutorial = 1005,
    Protocol__Enum_Account_SetTutorial = 1006,
    Protocol__Enum_Account_PassCheck = 1007,
    Protocol__Enum_Account_VerifyForYostar = 1008,
    Protocol__Enum_Account_CheckYostar = 1009,
    Protocol__Enum_Account_CallName = 1010,
    Protocol__Enum_Account_BirthDay = 1011,
    Protocol__Enum_Account_Auth2 = 1012,
    Protocol__Enum_Account_LinkReward = 1013,
    Protocol__Enum_Account_CheckNexon = 1014,
    Protocol__Enum_Account_DetachNexon = 1015,
    Protocol__Enum_Account_ReportXignCodeCheater = 1016,
    Protocol__Enum_Account_DismissRepurchasablePopup = 1017,
    Protocol__Enum_Account_InvalidateToken = 1018,
    Protocol__Enum_Account_LoginSync = 1019,
    Protocol__Enum_Account_VerifyCheckAdultAgree = 1020,
    Protocol__Enum_Account_SetCheckAdultAgree = 1021,
    Protocol__Enum_Account_Reset = 1022,
    Protocol__Enum_Account_RequestBirthdayMail = 1023,
    Protocol__Enum_Account_CheckAccountLevelReward = 1024,
    Protocol__Enum_Account_ReceiveAccountLevelReward = 1025,
    Protocol__Enum_Character_List = 2000,
    Protocol__Enum_Character_Transcendence = 2001,
    Protocol__Enum_Character_ExpGrowth = 2002,
    Protocol__Enum_Character_FavorGrowth = 2003,
    Protocol__Enum_Character_UpdateSkillLevel = 2004,
    Protocol__Enum_Character_UnlockWeapon = 2005,
    Protocol__Enum_Character_WeaponExpGrowth = 2006,
    Protocol__Enum_Character_WeaponTranscendence = 2007,
    Protocol__Enum_Character_SetFavorites = 2008,
    Protocol__Enum_Character_SetCostume = 2009,
    Protocol__Enum_Character_BatchSkillLevelUpdate = 2010,
    Protocol__Enum_Character_PotentialGrowth = 2011,
    Protocol__Enum_Equipment_List = 3000,
    Protocol__Enum_Equipment_Sell = 3001,
    Protocol__Enum_Equipment_Equip = 3002,
    Protocol__Enum_Equipment_LevelUp = 3003,
    Protocol__Enum_Equipment_TierUp = 3004,
    Protocol__Enum_Equipment_Lock = 3005,
    Protocol__Enum_Equipment_BatchGrowth = 3006,
    Protocol__Enum_Item_List = 4000,
    Protocol__Enum_Item_Sell = 4001,
    Protocol__Enum_Item_Consume = 4002,
    Protocol__Enum_Item_Lock = 4003,
    Protocol__Enum_Item_BulkConsume = 4004,
    Protocol__Enum_Item_SelectTicket = 4005,
    Protocol__Enum_Item_AutoSynth = 4006,
    Protocol__Enum_Echelon_List = 5000,
    Protocol__Enum_Echelon_Save = 5001,
    Protocol__Enum_Echelon_PresetList = 5002,
    Protocol__Enum_Echelon_PresetSave = 5003,
    Protocol__Enum_Echelon_PresetGroupRename = 5004,
    Protocol__Enum_Campaign_List = 6000,
    Protocol__Enum_Campaign_EnterMainStage = 6001,
    Protocol__Enum_Campaign_ConfirmMainStage = 6002,
    Protocol__Enum_Campaign_DeployEchelon = 6003,
    Protocol__Enum_Campaign_WithdrawEchelon = 6004,
    Protocol__Enum_Campaign_MapMove = 6005,
    Protocol__Enum_Campaign_EndTurn = 6006,
    Protocol__Enum_Campaign_EnterTactic = 6007,
    Protocol__Enum_Campaign_TacticResult = 6008,
    Protocol__Enum_Campaign_Retreat = 6009,
    Protocol__Enum_Campaign_ChapterClearReward = 6010,
    Protocol__Enum_Campaign_Heal = 6011,
    Protocol__Enum_Campaign_EnterSubStage = 6012,
    Protocol__Enum_Campaign_SubStageResult = 6013,
    Protocol__Enum_Campaign_Portal = 6014,
    Protocol__Enum_Campaign_ConfirmTutorialStage = 6015,
    Protocol__Enum_Campaign_PurchasePlayCountHardStage = 6016,
    Protocol__Enum_Campaign_EnterTutorialStage = 6017,
    Protocol__Enum_Campaign_TutorialStageResult = 6018,
    Protocol__Enum_Campaign_RestartMainStage = 6019,
    Protocol__Enum_Campaign_EnterMainStageStrategySkip = 6020,
    Protocol__Enum_Campaign_MainStageStrategySkipResult = 6021,
    Protocol__Enum_Mail_List = 7000,
    Protocol__Enum_Mail_Check = 7001,
    Protocol__Enum_Mail_Receive = 7002,
    Protocol__Enum_Mission_List = 8000,
    Protocol__Enum_Mission_Reward = 8001,
    Protocol__Enum_Mission_MultipleReward = 8002,
    Protocol__Enum_Mission_GuideReward = 8003,
    Protocol__Enum_Mission_MultipleGuideReward = 8004,
    Protocol__Enum_Mission_Sync = 8005,
    Protocol__Enum_Mission_GuideMissionSeasonList = 8006,
    Protocol__Enum_Attendance_List = 9000,
    Protocol__Enum_Attendance_Check = 9001,
    Protocol__Enum_Attendance_Reward = 9002,
    Protocol__Enum_Shop_BuyMerchandise = 10000,
    Protocol__Enum_Shop_BuyGacha = 10001,
    Protocol__Enum_Shop_List = 10002,
    Protocol__Enum_Shop_Refresh = 10003,
    Protocol__Enum_Shop_BuyEligma = 10004,
    Protocol__Enum_Shop_BuyGacha2 = 10005,
    Protocol__Enum_Shop_GachaRecruitList = 10006,
    Protocol__Enum_Shop_BuyRefreshMerchandise = 10007,
    Protocol__Enum_Shop_BuyGacha3 = 10008,
    Protocol__Enum_Shop_BuyAP = 10009,
    Protocol__Enum_Shop_BeforehandGachaGet = 10010,
    Protocol__Enum_Shop_BeforehandGachaRun = 10011,
    Protocol__Enum_Shop_BeforehandGachaSave = 10012,
    Protocol__Enum_Shop_BeforehandGachaPick = 10013,
    Protocol__Enum_Shop_PickupSelectionGachaGet = 10014,
    Protocol__Enum_Shop_PickupSelectionGachaSet = 10015,
    Protocol__Enum_Shop_PickupSelectionGachaBuy = 10016,
    Protocol__Enum_Recipe_Craft = 11000,
    Protocol__Enum_MemoryLobby_List = 12000,
    Protocol__Enum_MemoryLobby_SetMain = 12001,
    Protocol__Enum_MemoryLobby_UpdateLobbyMode = 12002,
    Protocol__Enum_MemoryLobby_Interact = 12003,
    Protocol__Enum_CumulativeTimeReward_List = 13000,
    Protocol__Enum_CumulativeTimeReward_Reward = 13001,
    Protocol__Enum_OpenCondition_List = 15000,
    Protocol__Enum_OpenCondition_Set = 15001,
    Protocol__Enum_OpenCondition_EventList = 15002,
    Protocol__Enum_Toast_List = 16000,
    Protocol__Enum_Raid_List = 17000,
    Protocol__Enum_Raid_CompleteList = 17001,
    Protocol__Enum_Raid_Detail = 17002,
    Protocol__Enum_Raid_Search = 17003,
    Protocol__Enum_Raid_CreateBattle = 17004,
    Protocol__Enum_Raid_EnterBattle = 17005,
    Protocol__Enum_Raid_BattleUpdate = 17006,
    Protocol__Enum_Raid_EndBattle = 17007,
    Protocol__Enum_Raid_Reward = 17008,
    Protocol__Enum_Raid_RewardAll = 17009,
    Protocol__Enum_Raid_Revive = 17010,
    Protocol__Enum_Raid_Share = 17011,
    Protocol__Enum_Raid_SeasonInfo = 17012,
    Protocol__Enum_Raid_SeasonReward = 17013,
    Protocol__Enum_Raid_Lobby = 17014,
    Protocol__Enum_Raid_GiveUp = 17015,
    Protocol__Enum_Raid_OpponentList = 17016,
    Protocol__Enum_Raid_RankingReward = 17017,
    Protocol__Enum_Raid_Login = 17018,
    Protocol__Enum_Raid_Sweep = 17019,
    Protocol__Enum_Raid_GetBestTeam = 17020,
    Protocol__Enum_Raid_RankingIndex = 17021,
    Protocol__Enum_SkipHistory_List = 18000,
    Protocol__Enum_SkipHistory_Save = 18001,
    Protocol__Enum_Scenario_List = 19000,
    Protocol__Enum_Scenario_Clear = 19001,
    Protocol__Enum_Scenario_GroupHistoryUpdate = 19002,
    Protocol__Enum_Scenario_Skip = 19003,
    Protocol__Enum_Scenario_Select = 19004,
    Protocol__Enum_Scenario_AccountStudentChange = 19005,
    Protocol__Enum_Scenario_LobbyStudentChange = 19006,
    Protocol__Enum_Scenario_SpecialLobbyChange = 19007,
    Protocol__Enum_Scenario_Enter = 19008,
    Protocol__Enum_Scenario_EnterMainStage = 19009,
    Protocol__Enum_Scenario_ConfirmMainStage = 19010,
    Protocol__Enum_Scenario_DeployEchelon = 19011,
    Protocol__Enum_Scenario_WithdrawEchelon = 19012,
    Protocol__Enum_Scenario_MapMove = 19013,
    Protocol__Enum_Scenario_EndTurn = 19014,
    Protocol__Enum_Scenario_EnterTactic = 19015,
    Protocol__Enum_Scenario_TacticResult = 19016,
    Protocol__Enum_Scenario_Retreat = 19017,
    Protocol__Enum_Scenario_Portal = 19018,
    Protocol__Enum_Scenario_RestartMainStage = 19019,
    Protocol__Enum_Scenario_SkipMainStage = 19020,
    Protocol__Enum_Cafe_Get = 20000,
    Protocol__Enum_Cafe_Ack = 20001,
    Protocol__Enum_Cafe_Deploy = 20002,
    Protocol__Enum_Cafe_Relocate = 20003,
    Protocol__Enum_Cafe_Remove = 20004,
    Protocol__Enum_Cafe_RemoveAll = 20005,
    Protocol__Enum_Cafe_Interact = 20006,
    Protocol__Enum_Cafe_ListPreset = 20007,
    Protocol__Enum_Cafe_RenamePreset = 20008,
    Protocol__Enum_Cafe_ClearPreset = 20009,
    Protocol__Enum_Cafe_UpdatePresetFurniture = 20010,
    Protocol__Enum_Cafe_ApplyPreset = 20011,
    Protocol__Enum_Cafe_RankUp = 20012,
    Protocol__Enum_Cafe_ReceiveCurrency = 20013,
    Protocol__Enum_Cafe_GiveGift = 20014,
    Protocol__Enum_Cafe_SummonCharacter = 20015,
    Protocol__Enum_Cafe_TrophyHistory = 20016,
    Protocol__Enum_Cafe_ApplyTemplate = 20017,
    Protocol__Enum_Cafe_Open = 20018,
    Protocol__Enum_Cafe_Travel = 20019,
    Protocol__Enum_Cafe_SummonCharacterTicketUse = 20020,
    Protocol__Enum_Cafe_PresetDetail = 20021,
    Protocol__Enum_Cafe_UpdateCopyPresetFurniture = 20022,
    Protocol__Enum_Craft_List = 21000,
    Protocol__Enum_Craft_SelectNode = 21001,
    Protocol__Enum_Craft_UpdateNodeLevel = 21002,
    Protocol__Enum_Craft_BeginProcess = 21003,
    Protocol__Enum_Craft_CompleteProcess = 21004,
    Protocol__Enum_Craft_Reward = 21005,
    Protocol__Enum_Craft_HistoryList = 21006,
    Protocol__Enum_Craft_ShiftingBeginProcess = 21007,
    Protocol__Enum_Craft_ShiftingCompleteProcess = 21008,
    Protocol__Enum_Craft_ShiftingReward = 21009,
    Protocol__Enum_Craft_AutoBeginProcess = 21010,
    Protocol__Enum_Craft_CompleteProcessAll = 21011,
    Protocol__Enum_Craft_RewardAll = 21012,
    Protocol__Enum_Craft_ShiftingCompleteProcessAll = 21013,
    Protocol__Enum_Craft_ShiftingRewardAll = 21014,
    Protocol__Enum_Craft_SavePreset = 21015,
    Protocol__Enum_Craft_SavePresetName = 21016,
    Protocol__Enum_Arena_EnterLobby = 22000,
    Protocol__Enum_Arena_Login = 22001,
    Protocol__Enum_Arena_SettingChange = 22002,
    Protocol__Enum_Arena_OpponentList = 22003,
    Protocol__Enum_Arena_EnterBattle = 22004,
    Protocol__Enum_Arena_EnterBattlePart1 = 22005,
    Protocol__Enum_Arena_EnterBattlePart2 = 22006,
    Protocol__Enum_Arena_BattleResult = 22007,
    Protocol__Enum_Arena_CumulativeTimeReward = 22008,
    Protocol__Enum_Arena_DailyReward = 22009,
    Protocol__Enum_Arena_RankList = 22010,
    Protocol__Enum_Arena_History = 22011,
    Protocol__Enum_Arena_RecordSync = 22012,
    Protocol__Enum_Arena_TicketPurchase = 22013,
    Protocol__Enum_Arena_DamageReport = 22014,
    Protocol__Enum_Arena_CheckSeasonCloseReward = 22015,
    Protocol__Enum_Arena_SyncEchelonSettingTime = 22016,
    Protocol__Enum_Arena_SettingAnonymous = 22017,
    Protocol__Enum_WeekDungeon_List = 23000,
    Protocol__Enum_WeekDungeon_EnterBattle = 23001,
    Protocol__Enum_WeekDungeon_BattleResult = 23002,
    Protocol__Enum_WeekDungeon_Retreat = 23003,
    Protocol__Enum_Academy_GetInfo = 24000,
    Protocol__Enum_Academy_AttendSchedule = 24001,
    Protocol__Enum_Academy_AttendFavorSchedule = 24002,
    Protocol__Enum_Event_GetList = 25000,
    Protocol__Enum_Event_GetImage = 25001,
    Protocol__Enum_Event_UseCoupon = 25002,
    Protocol__Enum_Event_RewardIncrease = 25003,
    Protocol__Enum_ContentSave_Get = 26000,
    Protocol__Enum_ContentSave_Discard = 26001,
    Protocol__Enum_ContentSweep_Request = 27000,
    Protocol__Enum_ContentSweep_MultiSweep = 27001,
    Protocol__Enum_ContentSweep_MultiSweepPresetList = 27002,
    Protocol__Enum_ContentSweep_SetMultiSweepPreset = 27003,
    Protocol__Enum_ContentSweep_SetMultiSweepPresetName = 27004,
    Protocol__Enum_Clan_Lobby = 28000,
    Protocol__Enum_Clan_Login = 28001,
    Protocol__Enum_Clan_Search = 28002,
    Protocol__Enum_Clan_Create = 28003,
    Protocol__Enum_Clan_Member = 28004,
    Protocol__Enum_Clan_Applicant = 28005,
    Protocol__Enum_Clan_Join = 28006,
    Protocol__Enum_Clan_Quit = 28007,
    Protocol__Enum_Clan_Permit = 28008,
    Protocol__Enum_Clan_Kick = 28009,
    Protocol__Enum_Clan_Setting = 28010,
    Protocol__Enum_Clan_Confer = 28011,
    Protocol__Enum_Clan_Dismiss = 28012,
    Protocol__Enum_Clan_AutoJoin = 28013,
    Protocol__Enum_Clan_MemberList = 28014,
    Protocol__Enum_Clan_CancelApply = 28015,
    Protocol__Enum_Clan_MyAssistList = 28016,
    Protocol__Enum_Clan_SetAssist = 28017,
    Protocol__Enum_Clan_ChatLog = 28018,
    Protocol__Enum_Clan_Check = 28019,
    Protocol__Enum_Clan_AllAssistList = 28020,
    Protocol__Enum_Billing_TransactionStartByYostar = 29000,
    Protocol__Enum_Billing_TransactionEndByYostar = 29001,
    Protocol__Enum_Billing_PurchaseListByYostar = 29002,
    Protocol__Enum_Billing_PurchaseCashShopVerifyByNexon = 29003,
    Protocol__Enum_Billing_CheckConditionCashShopGoods = 29004,
    Protocol__Enum_Billing_PurchaseListByNexon = 29005,
    Protocol__Enum_Billing_ValidateByNexon = 29006,
    Protocol__Enum_Billing_FinishByNexon = 29007,
    Protocol__Enum_Billing_PurchaseFreeProduct = 29008,
    Protocol__Enum_EventContent_AdventureList = 30000,
    Protocol__Enum_EventContent_EnterMainStage = 30001,
    Protocol__Enum_EventContent_ConfirmMainStage = 30002,
    Protocol__Enum_EventContent_EnterTactic = 30003,
    Protocol__Enum_EventContent_TacticResult = 30004,
    Protocol__Enum_EventContent_EnterSubStage = 30005,
    Protocol__Enum_EventContent_SubStageResult = 30006,
    Protocol__Enum_EventContent_DeployEchelon = 30007,
    Protocol__Enum_EventContent_WithdrawEchelon = 30008,
    Protocol__Enum_EventContent_MapMove = 30009,
    Protocol__Enum_EventContent_EndTurn = 30010,
    Protocol__Enum_EventContent_Retreat = 30011,
    Protocol__Enum_EventContent_Portal = 30012,
    Protocol__Enum_EventContent_PurchasePlayCountHardStage = 30013,
    Protocol__Enum_EventContent_ShopList = 30014,
    Protocol__Enum_EventContent_ShopRefresh = 30015,
    Protocol__Enum_EventContent_ReceiveStageTotalReward = 30016,
    Protocol__Enum_EventContent_EnterMainGroundStage = 30017,
    Protocol__Enum_EventContent_MainGroundStageResult = 30018,
    Protocol__Enum_EventContent_ShopBuyMerchandise = 30019,
    Protocol__Enum_EventContent_ShopBuyRefreshMerchandise = 30020,
    Protocol__Enum_EventContent_SelectBuff = 30021,
    Protocol__Enum_EventContent_BoxGachaShopList = 30022,
    Protocol__Enum_EventContent_BoxGachaShopPurchase = 30023,
    Protocol__Enum_EventContent_BoxGachaShopRefresh = 30024,
    Protocol__Enum_EventContent_CollectionList = 30025,
    Protocol__Enum_EventContent_CollectionForMission = 30026,
    Protocol__Enum_EventContent_ScenarioGroupHistoryUpdate = 30027,
    Protocol__Enum_EventContent_CardShopList = 30028,
    Protocol__Enum_EventContent_CardShopShuffle = 30029,
    Protocol__Enum_EventContent_CardShopPurchase = 30030,
    Protocol__Enum_EventContent_RestartMainStage = 30031,
    Protocol__Enum_EventContent_LocationGetInfo = 30032,
    Protocol__Enum_EventContent_LocationAttendSchedule = 30033,
    Protocol__Enum_EventContent_FortuneGachaPurchase = 30034,
    Protocol__Enum_EventContent_SubEventLobby = 30035,
    Protocol__Enum_EventContent_EnterStoryStage = 30036,
    Protocol__Enum_EventContent_StoryStageResult = 30037,
    Protocol__Enum_EventContent_DiceRaceLobby = 30038,
    Protocol__Enum_EventContent_DiceRaceRoll = 30039,
    Protocol__Enum_EventContent_DiceRaceLapReward = 30040,
    Protocol__Enum_EventContent_PermanentList = 30041,
    Protocol__Enum_EventContent_DiceRaceUseItem = 30042,
    Protocol__Enum_EventContent_CardShopPurchaseAll = 30043,
    Protocol__Enum_EventContent_TreasureLobby = 30044,
    Protocol__Enum_EventContent_TreasureFlip = 30045,
    Protocol__Enum_EventContent_TreasureNextRound = 30046,
    Protocol__Enum_EventContent_ConcentrationGetInfo = 30047,
    Protocol__Enum_EventContent_ConcentrationFlipCard = 30048,
    Protocol__Enum_EventContent_ConcentrationRoundComplete = 30049,
    Protocol__Enum_EventContent_ConcentrationRoundSkip = 30050,
    Protocol__Enum_TTS_GetFile = 31000,
    Protocol__Enum_TTS_GetKana = 31001,
    Protocol__Enum_ContentLog_UIOpenStatistics = 32000,
    Protocol__Enum_MomoTalk_OutLine = 33000,
    Protocol__Enum_MomoTalk_MessageList = 33001,
    Protocol__Enum_MomoTalk_Read = 33002,
    Protocol__Enum_MomoTalk_Reply = 33003,
    Protocol__Enum_MomoTalk_FavorSchedule = 33004,
    Protocol__Enum_ClearDeck_List = 34000,
    Protocol__Enum_MiniGame_StageList = 35000,
    Protocol__Enum_MiniGame_EnterStage = 35001,
    Protocol__Enum_MiniGame_Result = 35002,
    Protocol__Enum_MiniGame_MissionList = 35003,
    Protocol__Enum_MiniGame_MissionReward = 35004,
    Protocol__Enum_MiniGame_MissionMultipleReward = 35005,
    Protocol__Enum_MiniGame_ShootingLobby = 35006,
    Protocol__Enum_MiniGame_ShootingBattleEnter = 35007,
    Protocol__Enum_MiniGame_ShootingBattleResult = 35008,
    Protocol__Enum_MiniGame_ShootingSweep = 35009,
    Protocol__Enum_MiniGame_TableBoardSync = 35010,
    Protocol__Enum_MiniGame_TableBoardMove = 35011,
    Protocol__Enum_MiniGame_TableBoardEncounterInput = 35012,
    Protocol__Enum_MiniGame_TableBoardBattleEncounter = 35013,
    Protocol__Enum_MiniGame_TableBoardBattleRunAway = 35014,
    Protocol__Enum_MiniGame_TableBoardClearThema = 35015,
    Protocol__Enum_MiniGame_TableBoardUseItem = 35016,
    Protocol__Enum_MiniGame_TableBoardResurrect = 35017,
    Protocol__Enum_MiniGame_TableBoardSweep = 35018,
    Protocol__Enum_MiniGame_TableBoardMoveThema = 35019,
    Protocol__Enum_MiniGame_DreamMakerGetInfo = 35020,
    Protocol__Enum_MiniGame_DreamMakerNewGame = 35021,
    Protocol__Enum_MiniGame_DreamMakerRestart = 35022,
    Protocol__Enum_MiniGame_DreamMakerAttendSchedule = 35023,
    Protocol__Enum_MiniGame_DreamMakerDailyClosing = 35024,
    Protocol__Enum_MiniGame_DreamMakerEnding = 35025,
    Protocol__Enum_MiniGame_DefenseGetInfo = 35026,
    Protocol__Enum_MiniGame_DefenseEnterBattle = 35027,
    Protocol__Enum_MiniGame_DefenseBattleResult = 35028,
    Protocol__Enum_MiniGame_RoadPuzzleGetInfo = 35029,
    Protocol__Enum_MiniGame_RoadPuzzleTilePlace = 35030,
    Protocol__Enum_MiniGame_RoadPuzzleSaveStage = 35031,
    Protocol__Enum_MiniGame_RoadPuzzleClearStage = 35032,
    Protocol__Enum_MiniGame_CCGLobby = 35033,
    Protocol__Enum_MiniGame_CCGCreateGame = 35034,
    Protocol__Enum_MiniGame_CCGSweep = 35035,
    Protocol__Enum_MiniGame_CCGEnterStage = 35036,
    Protocol__Enum_MiniGame_CCGEndStageDual = 35037,
    Protocol__Enum_MiniGame_CCGEndStageEvent = 35038,
    Protocol__Enum_MiniGame_CCGSelectRewardCard = 35039,
    Protocol__Enum_Minigame_CCGReplaceCharacter = 35040,
    Protocol__Enum_MiniGame_CCGSelectCampAction = 35041,
    Protocol__Enum_MiniGame_CCGCompleteGame = 35042,
    Protocol__Enum_MiniGame_CCGGiveupGame = 35043,
    Protocol__Enum_MiniGame_CCGRerollReward = 35044,
    Protocol__Enum_MiniGame_CCGBuyPerk = 35045,
    Protocol__Enum_Notification_LobbyCheck = 36000,
    Protocol__Enum_Notification_EventContentReddotCheck = 36001,
    Protocol__Enum_ProofToken_RequestQuestion = 37000,
    Protocol__Enum_ProofToken_Submit = 37001,
    Protocol__Enum_SchoolDungeon_List = 38000,
    Protocol__Enum_SchoolDungeon_EnterBattle = 38001,
    Protocol__Enum_SchoolDungeon_BattleResult = 38002,
    Protocol__Enum_SchoolDungeon_Retreat = 38003,
    Protocol__Enum_TimeAttackDungeon_Lobby = 39000,
    Protocol__Enum_TimeAttackDungeon_CreateBattle = 39001,
    Protocol__Enum_TimeAttackDungeon_EnterBattle = 39002,
    Protocol__Enum_TimeAttackDungeon_EndBattle = 39003,
    Protocol__Enum_TimeAttackDungeon_Sweep = 39004,
    Protocol__Enum_TimeAttackDungeon_GiveUp = 39005,
    Protocol__Enum_TimeAttackDungeon_Login = 39006,
    Protocol__Enum_WorldRaid_Lobby = 40000,
    Protocol__Enum_WorldRaid_BossList = 40001,
    Protocol__Enum_WorldRaid_EnterBattle = 40002,
    Protocol__Enum_WorldRaid_BattleResult = 40003,
    Protocol__Enum_WorldRaid_ReceiveReward = 40004,
    Protocol__Enum_ResetableContent_Get = 41000,
    Protocol__Enum_Conquest_GetInfo = 42000,
    Protocol__Enum_Conquest_Conquer = 42001,
    Protocol__Enum_Conquest_ConquerWithBattleStart = 42002,
    Protocol__Enum_Conquest_ConquerWithBattleResult = 42003,
    Protocol__Enum_Conquest_DeployEchelon = 42004,
    Protocol__Enum_Conquest_ManageBase = 42005,
    Protocol__Enum_Conquest_UpgradeBase = 42006,
    Protocol__Enum_Conquest_TakeEventObject = 42007,
    Protocol__Enum_Conquest_EventObjectBattleStart = 42008,
    Protocol__Enum_Conquest_EventObjectBattleResult = 42009,
    Protocol__Enum_Conquest_ReceiveCalculateRewards = 42010,
    Protocol__Enum_Conquest_NormalizeEchelon = 42011,
    Protocol__Enum_Conquest_Check = 42012,
    Protocol__Enum_Conquest_ErosionBattleStart = 42013,
    Protocol__Enum_Conquest_ErosionBattleResult = 42014,
    Protocol__Enum_Conquest_MainStoryGetInfo = 42015,
    Protocol__Enum_Conquest_MainStoryConquer = 42016,
    Protocol__Enum_Conquest_MainStoryConquerWithBattleStart = 42017,
    Protocol__Enum_Conquest_MainStoryConquerWithBattleResult = 42018,
    Protocol__Enum_Conquest_MainStoryCheck = 42019,
    Protocol__Enum_Friend_List = 43000,
    Protocol__Enum_Friend_Remove = 43001,
    Protocol__Enum_Friend_GetFriendDetailedInfo = 43002,
    Protocol__Enum_Friend_GetIdCard = 43003,
    Protocol__Enum_Friend_SetIdCard = 43004,
    Protocol__Enum_Friend_Search = 43005,
    Protocol__Enum_Friend_SendFriendRequest = 43006,
    Protocol__Enum_Friend_AcceptFriendRequest = 43007,
    Protocol__Enum_Friend_DeclineFriendRequest = 43008,
    Protocol__Enum_Friend_CancelFriendRequest = 43009,
    Protocol__Enum_Friend_Check = 43010,
    Protocol__Enum_Friend_ListByIds = 43011,
    Protocol__Enum_Friend_Block = 43012,
    Protocol__Enum_Friend_Unblock = 43013,
    Protocol__Enum_CharacterGear_List = 44000,
    Protocol__Enum_CharacterGear_Unlock = 44001,
    Protocol__Enum_CharacterGear_TierUp = 44002,
    Protocol__Enum_EliminateRaid_Login = 45000,
    Protocol__Enum_EliminateRaid_Lobby = 45001,
    Protocol__Enum_EliminateRaid_OpponentList = 45002,
    Protocol__Enum_EliminateRaid_GetBestTeam = 45003,
    Protocol__Enum_EliminateRaid_CreateBattle = 45004,
    Protocol__Enum_EliminateRaid_EnterBattle = 45005,
    Protocol__Enum_EliminateRaid_EndBattle = 45006,
    Protocol__Enum_EliminateRaid_GiveUp = 45007,
    Protocol__Enum_EliminateRaid_Sweep = 45008,
    Protocol__Enum_EliminateRaid_SeasonReward = 45009,
    Protocol__Enum_EliminateRaid_RankingReward = 45010,
    Protocol__Enum_EliminateRaid_LimitedReward = 45011,
    Protocol__Enum_EliminateRaid_RankingIndex = 45012,
    Protocol__Enum_Attachment_Get = 46000,
    Protocol__Enum_Attachment_EmblemList = 46001,
    Protocol__Enum_Attachment_EmblemAcquire = 46002,
    Protocol__Enum_Attachment_EmblemAttach = 46003,
    Protocol__Enum_Sticker_Login = 47000,
    Protocol__Enum_Sticker_Lobby = 47001,
    Protocol__Enum_Sticker_UseSticker = 47002,
    Protocol__Enum_Field_Sync = 48000,
    Protocol__Enum_Field_Interaction = 48001,
    Protocol__Enum_Field_QuestClear = 48002,
    Protocol__Enum_Field_SceneChanged = 48003,
    Protocol__Enum_Field_EndDate = 48004,
    Protocol__Enum_Field_EnterStage = 48005,
    Protocol__Enum_Field_StageResult = 48006,
    Protocol__Enum_MultiFloorRaid_Sync = 49000,
    Protocol__Enum_MultiFloorRaid_EnterBattle = 49001,
    Protocol__Enum_MultiFloorRaid_EndBattle = 49002,
    Protocol__Enum_MultiFloorRaid_ReceiveReward = 49003,
    Protocol__Enum_MultiFloorRaid_Login = 49004,
    Protocol__Enum_Queuing_GetTicket = 50000,
    Protocol__Enum_Queuing_GetCryptoKeys = 50001,
    Protocol__Enum_BattlePass_GetInfo = 51000,
    Protocol__Enum_BattlePass_BuyLevel = 51001,
    Protocol__Enum_BattlePass_ReceiveReward = 51002,
    Protocol__Enum_BattlePass_MissionList = 51003,
    Protocol__Enum_BattlePass_MissionSingleReward = 51004,
    Protocol__Enum_BattlePass_MissionMultipleReward = 51005,
    Protocol__Enum_BattlePass_Check = 51006,
    Protocol__Enum_DailyRecord_Reward = 52000,
    Protocol__Enum_Option_Save = 53000,
    Protocol__Enum_Management_BannerList = 100000,
    Protocol__Enum_Management_ProtocolLockList = 100001,
} Protocol__Enum;

int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion0(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion1(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion2(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion3(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion4(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion5(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion6(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion7(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion8(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion9(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion10(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion11(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion12(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion13(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion14(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion15(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion16(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion17(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion18(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion19(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion20(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion21(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion22(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion23(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion24(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion25(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion26(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion27(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion28(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion29(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion30(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion31(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion32(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion33(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion34(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion35(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion36(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion37(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion38(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion39(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion40(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion41(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion42(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion43(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion44(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion45(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion46(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion47(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion48(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion49(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion50(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion51(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion52(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion53(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion54(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion55(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion56(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion57(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion58(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion59(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion60(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion61(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion62(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion63(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion64(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion65(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion66(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion67(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion68(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion69(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion70(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion71(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion72(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion73(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion74(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion75(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion76(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion77(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion78(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion79(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion80(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion81(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion82(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion83(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion84(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion85(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion86(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion87(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion88(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion89(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion90(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion91(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion92(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion93(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion94(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion95(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion96(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion97(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_typeConversion98(Protocol__Enum protocol) {
    return protocol;
}
int32_t MX_NetworkProtocol_ProtocolConverter_TypeConversion(uint32_t crc, Protocol__Enum protocol) {
    switch (crc % 99) {
        case 0: return MX_NetworkProtocol_ProtocolConverter_typeConversion0(protocol);
        case 1: return MX_NetworkProtocol_ProtocolConverter_typeConversion1(protocol);
        case 2: return MX_NetworkProtocol_ProtocolConverter_typeConversion2(protocol);
        case 3: return MX_NetworkProtocol_ProtocolConverter_typeConversion3(protocol);
        case 4: return MX_NetworkProtocol_ProtocolConverter_typeConversion4(protocol);
        case 5: return MX_NetworkProtocol_ProtocolConverter_typeConversion5(protocol);
        case 6: return MX_NetworkProtocol_ProtocolConverter_typeConversion6(protocol);
        case 7: return MX_NetworkProtocol_ProtocolConverter_typeConversion7(protocol);
        case 8: return MX_NetworkProtocol_ProtocolConverter_typeConversion8(protocol);
        case 9: return MX_NetworkProtocol_ProtocolConverter_typeConversion9(protocol);
        case 10: return MX_NetworkProtocol_ProtocolConverter_typeConversion10(protocol);
        case 11: return MX_NetworkProtocol_ProtocolConverter_typeConversion11(protocol);
        case 12: return MX_NetworkProtocol_ProtocolConverter_typeConversion12(protocol);
        case 13: return MX_NetworkProtocol_ProtocolConverter_typeConversion13(protocol);
        case 14: return MX_NetworkProtocol_ProtocolConverter_typeConversion14(protocol);
        case 15: return MX_NetworkProtocol_ProtocolConverter_typeConversion15(protocol);
        case 16: return MX_NetworkProtocol_ProtocolConverter_typeConversion16(protocol);
        case 17: return MX_NetworkProtocol_ProtocolConverter_typeConversion17(protocol);
        case 18: return MX_NetworkProtocol_ProtocolConverter_typeConversion18(protocol);
        case 19: return MX_NetworkProtocol_ProtocolConverter_typeConversion19(protocol);
        case 20: return MX_NetworkProtocol_ProtocolConverter_typeConversion20(protocol);
        case 21: return MX_NetworkProtocol_ProtocolConverter_typeConversion21(protocol);
        case 22: return MX_NetworkProtocol_ProtocolConverter_typeConversion22(protocol);
        case 23: return MX_NetworkProtocol_ProtocolConverter_typeConversion23(protocol);
        case 24: return MX_NetworkProtocol_ProtocolConverter_typeConversion24(protocol);
        case 25: return MX_NetworkProtocol_ProtocolConverter_typeConversion25(protocol);
        case 26: return MX_NetworkProtocol_ProtocolConverter_typeConversion26(protocol);
        case 27: return MX_NetworkProtocol_ProtocolConverter_typeConversion27(protocol);
        case 28: return MX_NetworkProtocol_ProtocolConverter_typeConversion28(protocol);
        case 29: return MX_NetworkProtocol_ProtocolConverter_typeConversion29(protocol);
        case 30: return MX_NetworkProtocol_ProtocolConverter_typeConversion30(protocol);
        case 31: return MX_NetworkProtocol_ProtocolConverter_typeConversion31(protocol);
        case 32: return MX_NetworkProtocol_ProtocolConverter_typeConversion32(protocol);
        case 33: return MX_NetworkProtocol_ProtocolConverter_typeConversion33(protocol);
        case 34: return MX_NetworkProtocol_ProtocolConverter_typeConversion34(protocol);
        case 35: return MX_NetworkProtocol_ProtocolConverter_typeConversion35(protocol);
        case 36: return MX_NetworkProtocol_ProtocolConverter_typeConversion36(protocol);
        case 37: return MX_NetworkProtocol_ProtocolConverter_typeConversion37(protocol);
        case 38: return MX_NetworkProtocol_ProtocolConverter_typeConversion38(protocol);
        case 39: return MX_NetworkProtocol_ProtocolConverter_typeConversion39(protocol);
        case 40: return MX_NetworkProtocol_ProtocolConverter_typeConversion40(protocol);
        case 41: return MX_NetworkProtocol_ProtocolConverter_typeConversion41(protocol);
        case 42: return MX_NetworkProtocol_ProtocolConverter_typeConversion42(protocol);
        case 43: return MX_NetworkProtocol_ProtocolConverter_typeConversion43(protocol);
        case 44: return MX_NetworkProtocol_ProtocolConverter_typeConversion44(protocol);
        case 45: return MX_NetworkProtocol_ProtocolConverter_typeConversion45(protocol);
        case 46: return MX_NetworkProtocol_ProtocolConverter_typeConversion46(protocol);
        case 47: return MX_NetworkProtocol_ProtocolConverter_typeConversion47(protocol);
        case 48: return MX_NetworkProtocol_ProtocolConverter_typeConversion48(protocol);
        case 49: return MX_NetworkProtocol_ProtocolConverter_typeConversion49(protocol);
        case 50: return MX_NetworkProtocol_ProtocolConverter_typeConversion50(protocol);
        case 51: return MX_NetworkProtocol_ProtocolConverter_typeConversion51(protocol);
        case 52: return MX_NetworkProtocol_ProtocolConverter_typeConversion52(protocol);
        case 53: return MX_NetworkProtocol_ProtocolConverter_typeConversion53(protocol);
        case 54: return MX_NetworkProtocol_ProtocolConverter_typeConversion54(protocol);
        case 55: return MX_NetworkProtocol_ProtocolConverter_typeConversion55(protocol);
        case 56: return MX_NetworkProtocol_ProtocolConverter_typeConversion56(protocol);
        case 57: return MX_NetworkProtocol_ProtocolConverter_typeConversion57(protocol);
        case 58: return MX_NetworkProtocol_ProtocolConverter_typeConversion58(protocol);
        case 59: return MX_NetworkProtocol_ProtocolConverter_typeConversion59(protocol);
        case 60: return MX_NetworkProtocol_ProtocolConverter_typeConversion60(protocol);
        case 61: return MX_NetworkProtocol_ProtocolConverter_typeConversion61(protocol);
        case 62: return MX_NetworkProtocol_ProtocolConverter_typeConversion62(protocol);
        case 63: return MX_NetworkProtocol_ProtocolConverter_typeConversion63(protocol);
        case 64: return MX_NetworkProtocol_ProtocolConverter_typeConversion64(protocol);
        case 65: return MX_NetworkProtocol_ProtocolConverter_typeConversion65(protocol);
        case 66: return MX_NetworkProtocol_ProtocolConverter_typeConversion66(protocol);
        case 67: return MX_NetworkProtocol_ProtocolConverter_typeConversion67(protocol);
        case 68: return MX_NetworkProtocol_ProtocolConverter_typeConversion68(protocol);
        case 69: return MX_NetworkProtocol_ProtocolConverter_typeConversion69(protocol);
        case 70: return MX_NetworkProtocol_ProtocolConverter_typeConversion70(protocol);
        case 71: return MX_NetworkProtocol_ProtocolConverter_typeConversion71(protocol);
        case 72: return MX_NetworkProtocol_ProtocolConverter_typeConversion72(protocol);
        case 73: return MX_NetworkProtocol_ProtocolConverter_typeConversion73(protocol);
        case 74: return MX_NetworkProtocol_ProtocolConverter_typeConversion74(protocol);
        case 75: return MX_NetworkProtocol_ProtocolConverter_typeConversion75(protocol);
        case 76: return MX_NetworkProtocol_ProtocolConverter_typeConversion76(protocol);
        case 77: return MX_NetworkProtocol_ProtocolConverter_typeConversion77(protocol);
        case 78: return MX_NetworkProtocol_ProtocolConverter_typeConversion78(protocol);
        case 79: return MX_NetworkProtocol_ProtocolConverter_typeConversion79(protocol);
        case 80: return MX_NetworkProtocol_ProtocolConverter_typeConversion80(protocol);
        case 81: return MX_NetworkProtocol_ProtocolConverter_typeConversion81(protocol);
        case 82: return MX_NetworkProtocol_ProtocolConverter_typeConversion82(protocol);
        case 83: return MX_NetworkProtocol_ProtocolConverter_typeConversion83(protocol);
        case 84: return MX_NetworkProtocol_ProtocolConverter_typeConversion84(protocol);
        case 85: return MX_NetworkProtocol_ProtocolConverter_typeConversion85(protocol);
        case 86: return MX_NetworkProtocol_ProtocolConverter_typeConversion86(protocol);
        case 87: return MX_NetworkProtocol_ProtocolConverter_typeConversion87(protocol);
        case 88: return MX_NetworkProtocol_ProtocolConverter_typeConversion88(protocol);
        case 89: return MX_NetworkProtocol_ProtocolConverter_typeConversion89(protocol);
        case 90: return MX_NetworkProtocol_ProtocolConverter_typeConversion90(protocol);
        case 91: return MX_NetworkProtocol_ProtocolConverter_typeConversion91(protocol);
        case 92: return MX_NetworkProtocol_ProtocolConverter_typeConversion92(protocol);
        case 93: return MX_NetworkProtocol_ProtocolConverter_typeConversion93(protocol);
        case 94: return MX_NetworkProtocol_ProtocolConverter_typeConversion94(protocol);
        case 95: return MX_NetworkProtocol_ProtocolConverter_typeConversion95(protocol);
        case 96: return MX_NetworkProtocol_ProtocolConverter_typeConversion96(protocol);
        case 97: return MX_NetworkProtocol_ProtocolConverter_typeConversion97(protocol);
        case 98: return MX_NetworkProtocol_ProtocolConverter_typeConversion98(protocol);
    }
}

#if defined(_WIN32) || defined(__CYGWIN__)
  #define EXPORT __declspec(dllexport)
#else
  #define EXPORT __attribute__((visibility("default")))
#endif

EXPORT int32_t TypeConversion(uint32_t crc, int protocol)
{
    return MX_NetworkProtocol_ProtocolConverter_TypeConversion(crc, (Protocol__Enum)protocol);
}

#ifdef BUILDING_PYTHON_EXTENSION

static PyObject* py_TypeConversion(PyObject* self, PyObject* args) {
    uint32_t crc;
    int protocol;

    if (!PyArg_ParseTuple(args, "Ii", &crc, &protocol)) {
        return NULL;
    }

    int32_t result = TypeConversion(crc, protocol);

    return PyLong_FromLong(result);
}

static PyMethodDef TypeConversionMethods[] = {
    {"TypeConversion", py_TypeConversion, METH_VARARGS,
     "Convert (crc, protocol) using MX_NetworkProtocol converter."},
    {NULL, NULL, 0, NULL}
};

static struct PyModuleDef TypeConversionModule = {
    PyModuleDef_HEAD_INIT,
    "TypeConversion",
    NULL,
    -1,
    TypeConversionMethods
};

PyMODINIT_FUNC PyInit_TypeConversion(void) {
    return PyModule_Create(&TypeConversionModule);
}

#endif
